SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{693686C8FA66C118}" {
   m_sEntityPrefab "{48CE75A9C6878E66}Prefabs/Groups/INDFOR/TT_Group_FIA_RifleSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{693686C8FA66C15D}" {
    }
    SCR_EntityCatalogSpawnerData "{693686C8FA66C15C}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{693686C87E4A5F7B}" {
   m_sEntityPrefab "{811A2866B3DB99B9}Prefabs/Groups/INDFOR/TT_Group_FIA_Platoon_HQ.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{693686C87E4A58BB}" {
    }
    SCR_EntityCatalogSpawnerData "{693686C87E4A58BD}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{693686C8546BED51}" {
   m_sEntityPrefab "{2EEC7A6DD55A6252}Prefabs/Groups/INDFOR/TT_Group_FIA_Crew.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{693686C8546BEE91}" {
    }
    SCR_EntityCatalogSpawnerData "{693686C8546BEE93}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}