SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569783D4C68630}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{693686C539AA2152}" {
     m_sEntityPrefab "{3A270294FF141506}Prefabs/Vehicles/Wheeled/BRDM2/TT_BRDM2_FIA.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{693686C539AA219C}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{693686C539AA2192}" {
       m_eSlotTypes 24
      }
     }
    }
   }
  }
 }
}