SCR_MissionHeader {
 World "{DF091602D62C62CC}Worlds/Arland/Demo.ent"
 m_sName "Triad Factions Demo World"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "A demo world for Triad Factions addon"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}