SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{691A8809BA6DC006}" {
   m_sEntityPrefab "{B4927424B27B945E}Prefabs/Characters/Factions/OPFOR/USSR_Army/Spetsnaz/TT_Character_USSR_SF_SL.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A8809BA6DC06D}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{691A8809BA6DC06F}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{691A88098AEC973F}" {
   m_sEntityPrefab "{2D8CCDBDAF9CA5CE}Prefabs/Characters/Factions/OPFOR/USSR_Army/Spetsnaz/TT_Character_USSR_SF_PL.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A88098AEC977F}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{691A88098AEC9761}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{691A8809802F481D}" {
   m_sEntityPrefab "{54B30E6BA41963E3}Prefabs/Characters/Factions/OPFOR/USSR_Army/Spetsnaz/TT_Character_USSR_SF_DPL.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A8809802F485A}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{691A8809802F485F}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{691A88099CFBA451}" {
   m_sEntityPrefab "{D1C72C10DA740A44}Prefabs/Characters/Factions/OPFOR/USSR_Army/Spetsnaz/TT_Character_USSR_SF.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A88099CFBA46A}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{691A88099CFBA46C}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{691A88075E4028B2}" {
   m_sEntityPrefab "{01B2ECFAF9762811}Prefabs/Characters/Factions/OPFOR/USSR_Army/Spetsnaz/TT_Character_USSR_SF_AT.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A88075E4028FB}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{691A88075E4028FD}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{691A88075CC4DE77}" {
   m_sEntityPrefab "{C98A98DCD7E8A8C7}Prefabs/Characters/Factions/OPFOR/USSR_Army/Spetsnaz/TT_Character_USSR_SF_SR.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A88075CC4DFB5}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{691A88075CC4DFB7}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{691A8807535C54CC}" {
   m_sEntityPrefab "{18E4A1A9823385FA}Prefabs/Characters/Factions/OPFOR/USSR_Army/Spetsnaz/TT_Character_USSR_SF_Driver.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A8807535C540E}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{691A8807535C5430}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}