SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{691A880473B71084}" {
   m_sEntityPrefab "{8D4BF4EB8875C4D0}Prefabs/Groups/OPFOR/TT_Group_USSR_Recon_BRDM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A880473B710C4}" {
    }
    SCR_EntityCatalogSpawnerData "{691A880473B710FA}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{691ADB95640D2E46}" {
   m_sEntityPrefab "{AECDDA030588F251}Prefabs/Groups/OPFOR/TT_Group_USSR_RifleSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691ADB95640D2E80}" {
    }
    SCR_EntityCatalogSpawnerData "{691ADB95640D2E86}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{691ADB957A1CAAF7}" {
   m_sEntityPrefab "{4069AB650949FF83}Prefabs/Groups/OPFOR/TT_Group_USSR_PL.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691ADB957A1CA932}" {
    }
    SCR_EntityCatalogSpawnerData "{691ADB957A1CA930}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{691A88044DF7B779}" {
   m_sEntityPrefab "{9D7A7CAA1EB9C5B3}Prefabs/Groups/OPFOR/TT_Group_USSR_Recon_PL_BRDM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A88044DF7B780}" {
    }
    SCR_EntityCatalogSpawnerData "{691A88044DF7B786}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{69254ABBDAF6A72D}" {
   m_sEntityPrefab "{00EED2BC36014B00}Prefabs/Groups/OPFOR/TT_Group_USSR_RifleSquad_Naval.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69254ABBDAF6A099}" {
    }
    SCR_EntityCatalogSpawnerData "{69254ABBDAF6A09B}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{69254ABB50F475FA}" {
   m_sEntityPrefab "{6EB364594D6B099D}Prefabs/Groups/OPFOR/TT_Group_USSR_PL_Naval.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69254ABB50F4753B}" {
    }
    SCR_EntityCatalogSpawnerData "{69254ABB50F4753A}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{69254ABB2FFF5E7A}" {
   m_sEntityPrefab "{3DDEB73AA033F34A}Prefabs/Groups/OPFOR/TT_Group_USSR_MG_Naval.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69254ABB2FFF5FB9}" {
    }
    SCR_EntityCatalogSpawnerData "{69254ABB2FFF5FBA}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{6926A95F601EBFC7}" {
   m_sEntityPrefab "{233C1FF7C03D41B6}Prefabs/Groups/OPFOR/TT_Group_USSR_Pilots.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6926A95F601EBF09}" {
    }
    SCR_EntityCatalogSpawnerData "{6926A95F601EBF0B}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}