SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{691A880473B71084}" {
   m_sEntityPrefab "{8D4BF4EB8875C4D0}Prefabs/Groups/OPFOR/TT_Group_USSR_Recon_BRDM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A880473B710C4}" {
    }
    SCR_EntityCatalogSpawnerData "{691A880473B710FA}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{691A88044DF7B779}" {
   m_sEntityPrefab "{9D7A7CAA1EB9C5B3}Prefabs/Groups/OPFOR/TT_Group_USSR_Recon_PL_BRDM.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691A88044DF7B780}" {
    }
    SCR_EntityCatalogSpawnerData "{691A88044DF7B786}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}