SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{605697836F02AFD9}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{691A8805CF8E956C}" {
     m_sEntityPrefab "{B9D67D95E24ED451}Prefabs/Vehicles/Wheeled/BRDM2/TT_BRDM2_Expl.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691A8805CF8E96AF}" {
      }
      SCR_EntityCatalogSpawnerData "{691A8805CF8E96D1}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{691ADB9B0759AF3B}" {
     m_sEntityPrefab "{A43D2AFEA85AD890}Prefabs/Vehicles/Wheeled/BTR70/BTR70_AGS17.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691ADB9B0759AF74}" {
      }
      SCR_EntityCatalogSpawnerData "{691ADB9B0759AF7B}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}