SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadModernFactions"
 m_sSourceDirectory "{C7BADD25707B02E3}Prefabs/Characters/Factions/INDFOR/NAPA"
 m_bExposed 1
 m_Prefabs {
  "{CE3DE03B34E4FA29}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_Rifleman.et"
  "{53E2512827E0DC3A}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_RiflemanAT.et"
  "{EB69B412503CD821}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_AT.et"
  "{B7EFA5368159A689}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_AAT.et"
  "{61D603C947FAD29E}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_MG.et"
  "{3D5012ED969FAC36}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_AMG.et"
  "{2351C0347EA258F7}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_SR.et"
  "{5E492CCC1B31646E}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_SL.et"
  "{78E9FFB51725B947}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_DPL.et"
  "{C757955506D655FE}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_PL.et"
  "{A9B4E4E8730C3269}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_Sniper.et"
  "{389C3E4B0DAA849E}Prefabs/Characters/Factions/INDFOR/NAPA/20s/TMF_Character_NAPA_Spotter.et"
 }
}