SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadModernFactions"
 m_sSourceDirectory "{39071C50690452DE}Prefabs/Characters/Factions/BLUFOR/CDF"
 m_bExposed 1
 m_Prefabs {
  "{D0A151B90F00DE6C}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_Rifleman.et"
  "{18C2FF67A3CBE7F6}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_RiflemanAT.et"
  "{15F88E9ECF9141E7}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_AAT.et"
  "{7E50A72369386BED}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_AT.et"
  "{9F473945D8574B58}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_AMG.et"
  "{F4EF10F87EFE6152}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_MG.et"
  "{55AE43979ED6AC73}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_Marksman.et"
  "{CB703FFD2235D7A2}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_SL.et"
  "{526E86643FD2E632}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_PL.et"
  "{DAFED41D59ED5E29}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_DPL.et"
  "{D7C03BA887D44A53}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_UAV.et"
  "{1CA684867BEAC81F}Prefabs/Characters/Factions/BLUFOR/CDF/20s/TMF_Character_CDF_Pilot.et"
 }
}