SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadModernFactions"
 m_sSourceDirectory "{C7BADD25707B02E3}Prefabs/Characters/Factions/INDFOR/NAPA"
 m_bExposed 1
 m_Prefabs {
  "{6F2DF0D5FA3A7807}Prefabs/Groups/INDFOR/TMF_Group_NAPA_RifleSquad.et"
  "{553AD4835A1908ED}Prefabs/Groups/INDFOR/TMF_Group_NAPA_PlatoonHQ.et"
  "{57738E239352FCDF}Prefabs/Groups/INDFOR/TMF_Group_NAPA_Sniper.et"
 }
}