SCR_PlaceableEntitiesRegistry {
 m_sAddon "TriadModernFactions"
 m_sSourceDirectory "{C7BADD25707B02E3}Prefabs/Characters/Factions/INDFOR/NAPA"
 m_bExposed 1
 m_Prefabs {
  "{014E03B63F83D1AD}Prefabs/Groups/BLUFOR/TMF_Group_CDF_RifleSquad.et"
  "{0266AD4EAA524057}Prefabs/Groups/BLUFOR/TMF_Group_CDF_PlatoonHQ.et"
 }
}