SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{69AF25F0A0887C35}" {
   m_sEntityPrefab "{9C01FD931EE3B8C2}Prefabs/Groups/BLUFOR/Group_USMC_2003_RifleSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69AF25F0A0887C75}" {
    }
    SCR_EntityCatalogSpawnerData "{69AF25F0A0887C77}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{69AF25F07A572297}" {
   m_sEntityPrefab "{B3E5AF3DA416DAF2}Prefabs/Groups/BLUFOR/Group_USMC_2003_PlatoonHQ.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69AF25F07A5722D0}" {
    }
    SCR_EntityCatalogSpawnerData "{69AF25F07A5722D1}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{69AF25FDEB277E74}" {
   m_sEntityPrefab "{531169C4590D1CFB}Prefabs/Groups/BLUFOR/Group_USMC_2003_Pilots.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69AF25FDEB277EBF}" {
    }
    SCR_EntityCatalogSpawnerData "{69AF25FDEB277EB9}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}