StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{691ADB8379628CA8}" {
   Id "TTF-Characters_AAR"
   Target_en_us "Assistant Machine Gunner"
   Modified 1763381505
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB92B56A65FF}" {
   Id "TTF-Characters_AAT"
   Target_en_us "Assistant Anti-Tank"
   Modified 1763373092
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB91BEE999CD}" {
   Id "TTF-Characters_AR"
   Target_en_us "Automatic Rifleman"
   Modified 1763372362
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB9145E1734A}" {
   Id "TTF-Characters_AT"
   Target_en_us "Rifleman Anti-Tank"
   Modified 1763372521
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB8CE68153AA}" {
   Id "TTF-Characters_Corpsman"
   Target_en_us "Corpsman"
   Modified 1763377783
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB9303FFFBC0}" {
   Id "TTF-Characters_Crew"
   Target_en_us "Crew"
   Modified 1763373807
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A880996DAE0BA}" {
   Id "TTF-Characters_DPL"
   Target_en_us "Deputy Platoon Leader"
   Modified 1763373983
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB8384852733}" {
   Id "TTF-Characters_MG"
   Target_en_us "Machine Gunner"
   Modified 1763381421
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A880BC63AF9F4}" {
   Id "TTF-Characters_PL"
   Target_en_us "Platoon Leader"
   Modified 1763373980
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807FD00CB31}" {
   Id "TTF-Characters_Recon"
   Target_en_us "Recon"
   Modified 1763352232
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807F0C2005C}" {
   Id "TTF-Characters_Recon_AT"
   Target_en_us "Recon (AT)"
   Modified 1763352258
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A88069E66D2A2}" {
   Id "TTF-Characters_Recon_Driver"
   Target_en_us "Recon (Driver)"
   Modified 1763353118
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807F7831AAD}" {
   Id "TTF-Characters_Recon_SR"
   Target_en_us "Senior Recon"
   Modified 1763352242
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB8BCC07B0E1}" {
   Id "TTF-Characters_RTO"
   Target_en_us "Radio Telephone Operator"
   Modified 1763377378
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807B1717AEF}" {
   Id "TTF-Characters_SL"
   Target_en_us "Squad Leader"
   Modified 1763352624
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB93E2A569A0}" {
   Id "TTF-Characters_Sniper"
   Target_en_us "Sniper"
   Modified 1763373409
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB909059B7E4}" {
   Id "TTF-Characters_SR"
   Target_en_us "Senior Rifleman"
   Modified 1763371987
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B1390B21F9138}" {
   Id "TTF-Characters_TL"
   Target_en_us "Team Leader"
   Modified 1763384167
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B1395B25CE193}" {
   Id "TTF-Groups_AntiTankSquad"
   Target_en_us "Anti Tank Squad"
   Modified 1763382798
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B13964A907020}" {
   Id "TTF-Groups_APC_Crew"
   Target_en_us "APC Crew"
   Modified 1763383381
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B139576E92815}" {
   Id "TTF-Groups_MG_Squad"
   Target_en_us "Machine Gun Squad"
   Modified 1763382921
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB95ECA803BC}" {
   Id "TTF-Groups_Platoon_HQ"
   Target_en_us "Platoon HQ"
   Modified 1763374308
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8804E5B5E52E}" {
   Id "TTF-Groups_Recon_BRDM"
   Target_en_us "Recon Squad (BRDM-2)"
   Modified 1763353851
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8804FC08EE22}" {
   Id "TTF-Groups_Recon_PL_BRDM"
   Target_en_us "Recon Platoon HQ (BRDM-2)"
   Modified 1763353880
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB9433A92B6E}" {
   Id "TTF-Groups_RifleSquad_V1"
   Target_en_us "Rifle Squad (Variant 1)"
   Modified 1763374242
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB940C79A00A}" {
   Id "TTF-Groups_RifleSquad_V2"
   Target_en_us "Rifle Squad (Variant 1)"
   Modified 1763374252
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8805C3904250}" {
   Id "TTF-Vehicles_BRMD2_Expl"
   Target_en_us "BRDM-2 (Explosives)"
   Modified 1763353462
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB9B186AB2EA}" {
   Id "TTF-Vehicles_BTR70_AGS"
   Target_en_us "BTR-70 (AGS-17)"
   Modified 1763370231
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B13925F6EBEC8}" {
   Id "TTF-Vehicles_M1025_Explosives"
   Target_en_us "M1025 (Explosives)"
   Modified 1763385495
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B139247318BF4}" {
   Id "TTF-Vehicles_M1025_Landmines"
   Target_en_us "M1025 (Landmines)"
   Modified 1763385479
   Author "siwi1"
   LastChanged "siwi1"
  }
 }
}