StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{691A8807FD00CB31}" {
   Id "TTF-Characters_Recon"
   Target_en_us "Recon"
   Modified 1763352232
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807F0C2005C}" {
   Id "TTF-Characters_Recon_AT"
   Target_en_us "Recon (AT)"
   Modified 1763352258
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A88069E66D2A2}" {
   Id "TTF-Characters_Recon_Driver"
   Target_en_us "Recon (Driver)"
   Modified 1763353118
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807F7831AAD}" {
   Id "TTF-Characters_Recon_SR"
   Target_en_us "Senior Recon"
   Modified 1763352242
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A880996DAE0BA}" {
   Id "TTF-Characters_SF_DPL"
   Target_en_us "Deputy Platoon Leader"
   Modified 1763347913
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A880BC63AF9F4}" {
   Id "TTF-Characters_SF_PL"
   Target_en_us "Platoon Leader"
   Modified 1763347917
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807B1717AEF}" {
   Id "TTF-Characters_SL"
   Target_en_us "Squad Leader"
   Modified 1763352624
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8804E5B5E52E}" {
   Id "TTF-Groups_Recon_BRDM"
   Target_en_us "Recon Squad (BRDM-2)"
   Modified 1763353851
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8804FC08EE22}" {
   Id "TTF-Groups_Recon_PL_BRDM"
   Target_en_us "Recon Platoon HQ (BRDM-2)"
   Modified 1763353880
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8805C3904250}" {
   Id "TTF-Vehicles_BRMD2_Expl"
   Target_en_us "BRDM-2 (Explosives)"
   Modified 1763353462
   Author "siwi1"
   LastChanged "siwi1"
  }
 }
}