StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{691ADB8379628CA8}" {
   Id "TTF-Characters_AAR"
   Target_en_us "Assistant Machine Gunner"
   Modified 1763381505
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB92B56A65FF}" {
   Id "TTF-Characters_AAT"
   Target_en_us "Assistant Anti-Tank"
   Modified 1764052550
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB2EECDEF9C}" {
   Id "TTF-Characters_AAT_Naval"
   Target_en_us "Assistant Anti-Tank (Naval)"
   Modified 1764053737
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{693686CC43361F35}" {
   Id "TTF-Characters_AMG"
   Target_en_us "Assistant Machine Gunner"
   Modified 1765181904
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254ABA0758700F}" {
   Id "TTF-Characters_AMG_Naval"
   Target_en_us "Assistant Machine Gunner (Naval)"
   Modified 1764057157
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69292E07AE332698}" {
   Id "TTF-Characters_AmmoBearer_Marines"
   Target_en_us "Ammo Bearer (Marine)"
   Modified 1764307748
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB91BEE999CD}" {
   Id "TTF-Characters_AR"
   Target_en_us "Automatic Rifleman"
   Modified 1763372362
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB3CB803AAE}" {
   Id "TTF-Characters_AR_Naval"
   Target_en_us "Automatic Rifleman (Naval)"
   Modified 1764053337
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB9145E1734A}" {
   Id "TTF-Characters_AT"
   Target_en_us "Rifleman Anti-Tank"
   Modified 1763372521
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB3AD446E9C}" {
   Id "TTF-Characters_AT_Naval"
   Target_en_us "Rifleman Anti-Tank (Naval)"
   Modified 1764053412
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB8CE68153AA}" {
   Id "TTF-Characters_Corpsman"
   Target_en_us "Corpsman"
   Modified 1763377783
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB9303FFFBC0}" {
   Id "TTF-Characters_Crew"
   Target_en_us "Crew"
   Modified 1763373807
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB309820795}" {
   Id "TTF-Characters_Crew_Naval"
   Target_en_us "Crew (Naval)"
   Modified 1764053683
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A880996DAE0BA}" {
   Id "TTF-Characters_DPL"
   Target_en_us "Deputy Platoon Leader"
   Modified 1763373983
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB365E71A9E}" {
   Id "TTF-Characters_DPL_Naval"
   Target_en_us "Deputy Platoon Leader (Naval)"
   Modified 1764053518
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9EDA6A549F3}" {
   Id "TTF-Characters_Grenadier_Marines"
   Target_en_us "Grenadier (Marine)"
   Modified 1764307678
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9EC50E6AB34}" {
   Id "TTF-Characters_Gunner"
   Target_en_us "Gunner"
   Modified 1764305221
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB8384852733}" {
   Id "TTF-Characters_MG"
   Target_en_us "Machine Gunner"
   Modified 1763381421
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254ABAD6EC5C5A}" {
   Id "TTF-Characters_MG_Naval"
   Target_en_us "Machine Gunner (Naval)"
   Modified 1764056583
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6926A95E5F89E287}" {
   Id "TTF-Characters_Pilot"
   Target_en_us "Pilot"
   Modified 1764141724
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A880BC63AF9F4}" {
   Id "TTF-Characters_PL"
   Target_en_us "Platoon Leader"
   Modified 1763373980
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB4DA8CC30B}" {
   Id "TTF-Characters_PL_Naval"
   Target_en_us "Platoon Leader (Naval)"
   Modified 1764053830
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB48021823A}" {
   Id "TTF-Characters_R_Naval"
   Target_en_us "Rifleman (Naval)"
   Modified 1764053929
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807FD00CB31}" {
   Id "TTF-Characters_Recon"
   Target_en_us "Recon"
   Modified 1763352232
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807F0C2005C}" {
   Id "TTF-Characters_Recon_AT"
   Target_en_us "Recon (AT)"
   Modified 1763352258
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A88069E66D2A2}" {
   Id "TTF-Characters_Recon_Driver"
   Target_en_us "Recon (Driver)"
   Modified 1763353118
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807F7831AAD}" {
   Id "TTF-Characters_Recon_SR"
   Target_en_us "Senior Recon"
   Modified 1763352242
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9F33262C704}" {
   Id "TTF-Characters_Rifleman_Marines"
   Target_en_us "Rifleman (Marine)"
   Modified 1764307714
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69367E430F27728D}" {
   Id "TTF-Characters_RiflemanAT"
   Target_en_us "Rifleman (AT)"
   Modified 1765180521
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9EEE596A73A}" {
   Id "TTF-Characters_RiflemanAT_Marines"
   Target_en_us "Rifleman AT (Marine)"
   Modified 1764307675
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB8BCC07B0E1}" {
   Id "TTF-Characters_RTO"
   Target_en_us "Radio Telephone Operator"
   Modified 1763377378
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9ECF190ACD9}" {
   Id "TTF-Characters_Section2IC_Marines"
   Target_en_us "Section 2IC (Marine)"
   Modified 1764307669
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9E65BCF5D86}" {
   Id "TTF-Characters_SectionCommander_Marines"
   Target_en_us "Section Commander (Marine)"
   Modified 1764307682
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8807B1717AEF}" {
   Id "TTF-Characters_SL"
   Target_en_us "Squad Leader"
   Modified 1763352624
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB4747708EA}" {
   Id "TTF-Characters_SL_Naval"
   Target_en_us "Squad Leader (Naval)"
   Modified 1764054018
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB93E2A569A0}" {
   Id "TTF-Characters_Sniper"
   Target_en_us "Sniper"
   Modified 1763373409
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB43BE2CE3E}" {
   Id "TTF-Characters_Sniper_Naval"
   Target_en_us "Sniper (Naval)"
   Modified 1764054111
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB909059B7E4}" {
   Id "TTF-Characters_SR"
   Target_en_us "Senior Rifleman"
   Modified 1763371987
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB4121D3AD9}" {
   Id "TTF-Characters_SR_Naval"
   Target_en_us "Senior Rifleman (Naval)"
   Modified 1764054183
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B1390B21F9138}" {
   Id "TTF-Characters_TL"
   Target_en_us "Team Leader"
   Modified 1763384167
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9E04B8ABC33}" {
   Id "TTF-Characters_TroopCommander"
   Target_en_us "Troop Commander"
   Modified 1764303348
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9E2636DC4FC}" {
   Id "TTF-Characters_TroopSergant"
   Target_en_us "Troop Sergant"
   Modified 1764304216
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9E3D2353ECF}" {
   Id "TTF-Characters_TroopSignaller"
   Target_en_us "Troop Signaller"
   Modified 1764304534
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B1395B25CE193}" {
   Id "TTF-Groups_AntiTankSquad"
   Target_en_us "Anti Tank Squad"
   Modified 1763382798
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B13964A907020}" {
   Id "TTF-Groups_APC_Crew"
   Target_en_us "APC Crew"
   Modified 1763383381
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254ABB7E41D063}" {
   Id "TTF-Groups_MG_Naval"
   Target_en_us "Machine Gun Squad (Naval)"
   Modified 1764057458
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B139576E92815}" {
   Id "TTF-Groups_MG_Squad"
   Target_en_us "Machine Gun Squad"
   Modified 1763382921
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69292E072FE38639}" {
   Id "TTF-Groups_MGSection_Marines"
   Target_en_us "MG Section (Marines)"
   Modified 1764308001
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6926A95FB950D31B}" {
   Id "TTF-Groups_Pilots"
   Target_en_us "Pilots"
   Modified 1764142023
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB95ECA803BC}" {
   Id "TTF-Groups_Platoon_HQ"
   Target_en_us "Platoon HQ"
   Modified 1763374308
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB8028187E9}" {
   Id "TTF-Groups_Platoon_HQ_Naval"
   Target_en_us "Platoon HQ (Naval)"
   Modified 1764055990
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8804E5B5E52E}" {
   Id "TTF-Groups_Recon_BRDM"
   Target_en_us "Recon Squad (BRDM-2)"
   Modified 1763353851
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8804FC08EE22}" {
   Id "TTF-Groups_Recon_PL_BRDM"
   Target_en_us "Recon Platoon HQ (BRDM-2)"
   Modified 1763353880
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9ED6D6DFAA8}" {
   Id "TTF-Groups_RifleSection_Marines"
   Target_en_us "Rifle Section (Marines)"
   Modified 1764307937
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{693686C5FB77AE3E}" {
   Id "TTF-Groups_RifleSquad"
   Target_en_us "Rifle Squad"
   Modified 1765185098
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254AB54B965F07}" {
   Id "TTF-Groups_RifleSquad_Naval"
   Target_en_us "Rifle Squad (Naval)"
   Modified 1764054483
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB9433A92B6E}" {
   Id "TTF-Groups_RifleSquad_V1"
   Target_en_us "Rifle Squad (Variant 1)"
   Modified 1763374242
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB940C79A00A}" {
   Id "TTF-Groups_RifleSquad_V2"
   Target_en_us "Rifle Squad (Variant 1)"
   Modified 1763374252
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{6928F9ED29ED4C69}" {
   Id "TTF-Groups_TroopHQ_Marines"
   Target_en_us "Troop HQ"
   Modified 1764305690
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691A8805C3904250}" {
   Id "TTF-Vehicles_BRMD2_Expl"
   Target_en_us "BRDM-2 (Explosives)"
   Modified 1763353462
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69254ABC73E75491}" {
   Id "TTF-Vehicles_BTR70"
   Target_en_us "BTR-70"
   Modified 1764057932
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691ADB9B186AB2EA}" {
   Id "TTF-Vehicles_BTR70_AGS"
   Target_en_us "BTR-70 (AGS-17)"
   Modified 1763370231
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69292E0336F25827}" {
   Id "TTF-Vehicles_LandRover_Recce_M2"
   Target_en_us "Land Rover Recce M2 (Fixed)"
   Modified 1764309838
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B13925F6EBEC8}" {
   Id "TTF-Vehicles_M1025_Explosives"
   Target_en_us "M1025 (Explosives)"
   Modified 1763385495
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{691B139247318BF4}" {
   Id "TTF-Vehicles_M1025_Landmines"
   Target_en_us "M1025 (Landmines)"
   Modified 1763385479
   Author "siwi1"
   LastChanged "siwi1"
  }
 }
}