StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{69E953A41002A8F9}" {
   Id "TMF_Characters_AAT"
   Target_en_us "Assistant Anti-Tank"
   Modified 1776902912
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB3912A7A6C33E}" {
   Id "TMF_Characters_AMG"
   Target_en_us "Assistant Machine Gunner"
   Modified 1777025940
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69E953A7ABF6BC4D}" {
   Id "TMF_Characters_AT"
   Target_en_us "Anti-Tank"
   Modified 1776900938
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB391A4487A692}" {
   Id "TMF_Characters_DPL"
   Target_en_us "Deputy Platoon Leader"
   Modified 1777030038
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EF39C3DC18276D}" {
   Id "TMF_Characters_Marksman"
   Target_en_us "Marksman"
   Modified 1777286578
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB3915B81F42C9}" {
   Id "TMF_Characters_MG"
   Target_en_us "Machine Gunner"
   Modified 1777024332
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB391AFA8AA7DE}" {
   Id "TMF_Characters_PL"
   Target_en_us "Platoon Leader"
   Modified 1777029766
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69E9463FF9A13A3C}" {
   Id "TMF_Characters_Rifleman"
   Target_en_us "Rifleman"
   Modified 1776898137
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69E9463FCFE9FE6B}" {
   Id "TMF_Characters_RiflemanAT"
   Target_en_us "Rifleman AT"
   Modified 1776898160
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB391C167B7B6F}" {
   Id "TMF_Characters_SL"
   Target_en_us "Squad Leader"
   Modified 1777029258
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB58A06B223064}" {
   Id "TMF_Characters_Sniper"
   Target_en_us "Sniper"
   Modified 1777032485
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB58A354514D3B}" {
   Id "TMF_Characters_Spotter"
   Target_en_us "Spotter"
   Modified 1777032129
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB391FCE09E683}" {
   Id "TMF_Characters_SR"
   Target_en_us "Senior Rifleman"
   Modified 1777027239
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EF39C44BE10D47}" {
   Id "TMF_Characters_UAV"
   Target_en_us "Drone Operator"
   Modified 1777288431
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69ED39138B8843C2}" {
   Id "TMF_Factions_CDF"
   Target_en_us "CDF"
   Modified 1777154962
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69E93B13A0A6AFBF}" {
   Id "TMF_Factions_NAPA"
   Target_en_us "NAPA"
   Modified 1776893290
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25FE24F00337}" {
   Id "TMF_Groups_Pilots"
   Target_en_us "Pilots"
   Modified 1773090948
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB58A18713AE36}" {
   Id "TMF_Groups_PlatoonHQ"
   Target_en_us "Platoon HQ"
   Modified 1777032916
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB58A1ECAA13D2}" {
   Id "TMF_Groups_RifleSquad"
   Target_en_us "Rifle Squad"
   Modified 1777032722
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB58A61E9B960F}" {
   Id "TMF_Groups_Snipers"
   Target_en_us "Snipers"
   Modified 1777033851
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25FED47E9946}" {
   Id "TMF_Pilot"
   Target_en_us "Pilot"
   Modified 1773090917
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69E946392150E67A}" {
   Id "TMF_Radio_Hand_NAPA"
   Target_en_us "Handheld Radio (NAPA)"
   Modified 1776897305
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69EB391C803ED432}" {
   Id "TMF_Radio_Hand_NAPA_SL"
   Target_en_us "Handheld Radio (NAPA, SL)"
   Modified 1777028756
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F332BCF600}" {
   Id "TMF_USMC_AMG_2003"
   Target_en_us "Assistant Automatic Rifleman"
   Modified 1773088459
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F168743C9E}" {
   Id "TMF_USMC_DPL_2003"
   Target_en_us "Deputy Platoon Leader (USMC, 2003)"
   Modified 1773089461
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F09BCE242B}" {
   Id "TMF_USMC_Groups_HQ"
   Target_en_us "Platoon HQ (USMC, 2003)"
   Modified 1773089881
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F10B5E007C}" {
   Id "TMF_USMC_Groups_RifleSquad"
   Target_en_us "Rifle Squad (USMC, 2003)"
   Modified 1773089623
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F50FDABBC9}" {
   Id "TMF_USMC_MG_2003"
   Target_en_us "Automatic Rifleman (USMC, 2003)"
   Modified 1773087536
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F1D3CEA813}" {
   Id "TMF_USMC_PL_2003"
   Target_en_us "Platoon Leader (USMC, 2003)"
   Modified 1773089320
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AD58159E1CE2F9}" {
   Id "TMF_USMC_Rifleman_2003"
   Target_en_us "Rifleman (USMC, 2003)"
   Modified 1772968627
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AD5D867745513E}" {
   Id "TMF_USMC_Rifleman_AT_2003"
   Target_en_us "Rifleman AT (USMC, 2003)"
   Modified 1772969628
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F2017106BC}" {
   Id "TMF_USMC_SL_2003"
   Target_en_us "Squad Leader (USMC, 2003)"
   Modified 1773089181
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AD5D84140F8055}" {
   Id "TMF_USMC_TeamLeader_2003"
   Target_en_us "Team Leader (USMC, 2003)"
   Modified 1772970980
   Author "siwi1"
   LastChanged "siwi1"
  }
 }
}