StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{69AF25FE24F00337}" {
   Id "TMF_Groups_Pilots"
   Target_en_us "Pilots"
   Modified 1773090948
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25FED47E9946}" {
   Id "TMF_Pilot"
   Target_en_us "Pilot"
   Modified 1773090917
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F332BCF600}" {
   Id "TMF_USMC_AMG_2003"
   Target_en_us "Assistant Automatic Rifleman"
   Modified 1773088459
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F168743C9E}" {
   Id "TMF_USMC_DPL_2003"
   Target_en_us "Deputy Platoon Leader (USMC, 2003)"
   Modified 1773089461
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F09BCE242B}" {
   Id "TMF_USMC_Groups_HQ"
   Target_en_us "Platoon HQ (USMC, 2003)"
   Modified 1773089881
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F10B5E007C}" {
   Id "TMF_USMC_Groups_RifleSquad"
   Target_en_us "Rifle Squad (USMC, 2003)"
   Modified 1773089623
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F50FDABBC9}" {
   Id "TMF_USMC_MG_2003"
   Target_en_us "Automatic Rifleman (USMC, 2003)"
   Modified 1773087536
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F1D3CEA813}" {
   Id "TMF_USMC_PL_2003"
   Target_en_us "Platoon Leader (USMC, 2003)"
   Modified 1773089320
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AD58159E1CE2F9}" {
   Id "TMF_USMC_Rifleman_2003"
   Target_en_us "Rifleman (USMC, 2003)"
   Modified 1772968627
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AD5D867745513E}" {
   Id "TMF_USMC_Rifleman_AT_2003"
   Target_en_us "Rifleman AT (USMC, 2003)"
   Modified 1772969628
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AF25F2017106BC}" {
   Id "TMF_USMC_SL_2003"
   Target_en_us "Squad Leader (USMC, 2003)"
   Modified 1773089181
   Author "siwi1"
   LastChanged "siwi1"
  }
  CustomStringTableItem "{69AD5D84140F8055}" {
   Id "TMF_USMC_TeamLeader_2003"
   Target_en_us "Team Leader (USMC, 2003)"
   Modified 1772970980
   Author "siwi1"
   LastChanged "siwi1"
  }
 }
}