SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{691B1397F8F6D591}" {
   m_sEntityPrefab "{CBD2888396F1ADA6}Prefabs/Groups/BLUFOR/TT_Group_USMC_AT_Squad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691B1397F8F6D5C2}" {
    }
    SCR_EntityCatalogSpawnerData "{691B1397F8F6D5C4}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{691B1397F28A09DB}" {
   m_sEntityPrefab "{3E633C93DBB63042}Prefabs/Groups/BLUFOR/TT_Group_USMC_Crew.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691B1397F28A0916}" {
    }
    SCR_EntityCatalogSpawnerData "{691B1397F28A0918}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{691B1397CF9E6B44}" {
   m_sEntityPrefab "{DFF2BB85468B1D49}Prefabs/Groups/BLUFOR/TT_Group_USMC_MG_Squad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691B1397CF9E749D}" {
    }
    SCR_EntityCatalogSpawnerData "{691B1397CF9E749F}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{691B1397CBF903C3}" {
   m_sEntityPrefab "{DB3A117F4DE37A9D}Prefabs/Groups/BLUFOR/TT_Group_USMC_PL_HQ.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691B1397CBF9031C}" {
    }
    SCR_EntityCatalogSpawnerData "{691B1397CBF9031E}" {
     m_eSlotTypes 7
    }
   }
  }
  SCR_EntityCatalogEntry "{691B1397C94FFF55}" {
   m_sEntityPrefab "{4CAF4192B4B4B3B6}Prefabs/Groups/BLUFOR/TT_Group_USMC_RifleSquad.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{691B1397C94FF894}" {
    }
    SCR_EntityCatalogSpawnerData "{691B1397C94FF899}" {
     m_eSlotTypes 7
    }
   }
  }
 }
}