SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{60569780DE4EE17A}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{691B139268045230}" {
     m_sEntityPrefab "{0F772CCA46429C03}Prefabs/Vehicles/Wheeled/LAV25/TT_LAV25_base.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691B139268045DF5}" {
       m_eValidEditorModes EDIT
      }
      SCR_EntityCatalogSpawnerData "{691B139268045D89}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{691B1392626D4480}" {
     m_sEntityPrefab "{31C4EE667A6E82C8}Prefabs/Vehicles/Wheeled/M998/TT_M1025_armed_M2HB.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691B1392626D4442}" {
       m_eValidEditorModes EDIT
      }
      SCR_EntityCatalogSpawnerData "{691B1392626D4440}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{691B13927CC193E1}" {
     m_sEntityPrefab "{FB08465031FA4C00}Prefabs/Vehicles/Wheeled/M998/TT_M1025_Explosives.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691B13927CC193AE}" {
       m_eValidEditorModes EDIT
      }
      SCR_EntityCatalogSpawnerData "{691B13927CC193AC}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
    SCR_EntityCatalogEntry "{691B139279305C17}" {
     m_sEntityPrefab "{FB08465031FA4BFF}Prefabs/Vehicles/Wheeled/M998/TT_M1025_Landmines.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{691B139279305FDC}" {
       m_eValidEditorModes EDIT
      }
      SCR_EntityCatalogSpawnerData "{691B139279305FD2}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}