SCR_EntityCatalogMultiList {
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{6928F9EFDBB5FD7A}" {
   m_sEntityPrefab "{3894DF9CE9CBD5AD}Prefabs/Groups/BLUFOR/British Forces/1989/Group_UK_1989_Marines_RifleSection.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6928F9EFDBB5FDB1}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6928F9EFDBB5FDAE}" {
     m_eSlotTypes 7
     m_iEntityCount 2
    }
   }
  }
  SCR_EntityCatalogEntry "{6928F9EFDB510E50}" {
   m_sEntityPrefab "{2BF90B60E97135B8}Prefabs/Groups/BLUFOR/British Forces/1989/Group_UK_1989_Marines_TroopHQ.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6928F9EFDB510E8C}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{6928F9EFDB510E8A}" {
     m_eSlotTypes 7
     m_iEntityCount 2
    }
   }
  }
  SCR_EntityCatalogEntry "{69292E06D799F7A9}" {
   m_sEntityPrefab "{B5BF36698DDC1090}Prefabs/Groups/BLUFOR/British Forces/1989/Group_UK_1989_Marines_MGSection.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69292E06D799F71B}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{69292E06D799F71F}" {
     m_eSlotTypes 7
     m_iEntityCount 2
    }
   }
  }
  SCR_EntityCatalogEntry "{69292E011DEFAFFD}" {
   m_sEntityPrefab "{8178FA7643337352}Prefabs/Groups/BLUFOR/British Forces/1989/Group_UK_1989_Pilots.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{69292E011DEFAF3F}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{69292E011DEFAF20}" {
     m_eSlotTypes 7
     m_iEntityCount 2
    }
   }
  }
 }
}