SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{649E99C2E04642C3}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{69292E02F8C5A53F}" {
     m_sEntityPrefab "{6FD91EB9002C3134}Prefabs/Vehicles/Wheeled/LR_3Series/TT_3Series_LWB_Recce_M2HB_Fixed.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{69292E02F8C5A57C}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{69292E02F8C5A563}" {
       m_eSlotTypes VEHICLE_MEDIUM
      }
     }
    }
   }
  }
 }
}