SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 FactionKey "CDF"
 UIInfo SCR_FactionUIInfo "{69ED3913835B8697}" {
  Name "#TMF_Factions_CDF"
  Icon "{988A09838BDA2D93}UI/CDF_Flag_Icon_BCR.edds"
 }
 "Identity of soldiers" FactionIdentity "{69ED3910CC0A3C36}" : "{FBBCD73926989580}Configs/Identities/FactionIdentity_USSR.conf" {
 }
 "Radio encryption key" "cherno"
 m_iOrder 4000
 m_sFactionFlag "{4523219D8762CFEC}UI/CDF_Flag_800400_BCR.edds"
 m_FactionFlagMaterial "{1D4A447A3E34C70D}Assets/Props/Fabric/Flags/Data/Flag_1_2_CDF.emat"
 m_FactionLabel FACTION_CDF
 m_eShowInWelcomeScreenOverride ALWAYSSHOW
 m_CallsignInfo SCR_FactionCallsignInfo "{69ED3916999DA178}" : "{958043CE1648EC43}Configs/Callsigns/Callsigns_USSR.conf" {
 }
 m_iFactionRadioFrequency 54000
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{69ED391676083B8C}" : "{31FC78AF00523A99}Configs/Identities/Territories/FactionHomeTerritory_USSR.conf" {
 }
}