SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "NAPA"
 UIInfo SCR_FactionUIInfo "{69E93B13B8ED1A4B}" {
  Name "#TMF_Factions_NAPA"
  Icon "{E25DC9DC6909EDE1}UI/NAPA_Flag_Icon_BCR.edds"
 }
 "Identity of soldiers" FactionIdentity "{69E93B10D2F1A2AA}" : "{FBBCD73926989580}Configs/Identities/FactionIdentity_USSR.conf" {
 }
 "Radio encryption key" "skalka"
 m_sFactionFlag "{E25DC9DC6909EDE1}UI/NAPA_Flag_Icon_BCR.edds"
 m_FactionFlagMaterial "{4A4C10958E6E1882}Assets/Props/Fabric/Flags/Data/Flag_1_2_NAPA.emat"
 m_FactionLabel FACTION_NAPA
 m_CallsignInfo SCR_FactionCallsignInfo "{69E93B1181C16807}" : "{958043CE1648EC43}Configs/Callsigns/Callsigns_USSR.conf" {
 }
 m_iFactionRadioFrequency 52000
 m_FactionHomeTerritoryConfig SCR_FactionHomeTerritoryConfig "{69E93B1161DBB3EB}" : "{31FC78AF00523A99}Configs/Identities/Territories/FactionHomeTerritory_USSR.conf" {
 }
}