SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{69E93B113E9A0CAF}" {
   m_Info SCR_UIInfo "{69E93B1133050499}" {
    Name "#TMF_Factions_NAPA"
    Icon "{E25DC9DC6909EDE1}UI/NAPA_Flag_Icon_BCR.edds"
   }
   m_Order 5
   m_LabelType FACTION_NAPA
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
  SCR_EditableEntityCoreLabelSettingExtended "{69ED4AD6DBE8A326}" {
   m_Info SCR_UIInfo "{69ED4AD6DBE8A365}" {
    Name "#TMF_Factions_CDF"
    Icon "{988A09838BDA2D93}UI/CDF_Flag_Icon_BCR.edds"
   }
   m_Order 4
   m_LabelType FACTION_CDF
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
 }
}